[bot]
token = "TOKEN"
owners = [ "000000000000000000" ]


[auth]
# 認証の結果を通知するチャンネルID
log_channel_id = "000000000000000000"
# 認証後に付与するロールID
role_id = "000000000000000000"
# マッチしたら認証成功とする正規表現
keyword = "あいことば"
# モーダルのデフォルト値にランダムに選択させるダミーのキーワード郡
dummy_keywords = [ "ダミー", "dummy" ]


[auto_kick]
# キック対象のギルドID
guild_id = "000000000000000000"
# 参加してからキックされるまでの猶予時間 (例: "12h" なら12時間) (1時間に一度チェックされる)
grace_period = "12h"
# キックされた際にDMへ送信するメッセージ
kick_message = """てすとサーバー にて合言葉の入力が確認できなかったため、自動的にキックされました。
再度参加する場合は、以下のリンクから再度参加してください。
https://example.com/
"""


[honeypot]
# ハニーポットのチャンネルID
channel_id = "000000000000000000"
# 削除対象にする同一内容の過去メッセージの送信された期間 (例: "24h" なら24時間以内)
message_lookback = "24h"
# キックされた際にDMへ送信するメッセージ
kick_message = """アカウントが乗っ取られたとみられる行動を確認したため、「てすとサーバー」から自動的にキックされました。"""
# ログを残すチャンネルID
log_channel_id = "000000000000000000"


[message_logging]
# メッセージの削除・編集のログを残すチャンネルID
channel_id = "000000000000000000"


[message_cache]
# 過去メッセージのキャッシュを無効化するかどうか
disabled = false
# 過去のメッセージのキャッシュを取るギルドIDのリスト
# target_guild_ids = ["651286346861641735"]
target_guild_ids = [ "000000000000000000" ]
# リクエスト数を制限する時間枠
request_window = "5s"
# 時間枠内で許可するリクエスト数
requests_per_window = 5
# 同時に過去メッセージを取得するチャンネル数
concurrent_channels = 20


[pin]
# チャンネルのオーナーを指定する
channels = [
    { id = "1318964564095930419", owner = "422735871410700308" }, # テスト
]


[thread_auto_invite]
# ロールの追加削除のトリガーとなるロールID
display_role_id = "000000000000000000"
# それぞれのロールを付与できるメンバーの数 (2500人のサーバでのテストの結果、250人以上にすると招待されない)
min_member_count = 250
# 実際に呼び出されるロールのID
role_ids = [ "000000000000000000", "000000000000000000" ]


[question]
# 質問の投稿先フォーラムのID
forum_id = "000000000000000000"
# 解決済みのタグID
solved_tag = "000000000000000000"
# 解決済みスレッド名の先頭につく文字
solved_name_prefix = "✅️ "
