name: CI

permissions:
  contents: read

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
  check:
    name: Cargo check (${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install cross compiler
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      # rustをインストール
      - name: Install Rust toolchain
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          cache-target: debug
          cache-extra-identifier: check-${{ matrix.target }}
          target-dirs: target
          targets: ${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Check
        run: cargo check --locked --all-targets --target ${{ matrix.target }}
